name: Test-site-lundgren
favicon: null
layout_spectrum: 0.92203
typography_spectrum: 0.5401355572976172
title: Sample
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#94dee1'
    - '#41bbbc'
    - '#2b4d60'
    - '#040404'
    - '#b08773'
  brandStrength: 0.625
  lightness: 0.75
  saturation: 0.6700498952995986
  rhythmicContrast: 0.25
purpose: []
