name: Test-site-lundgren
favicon: null
layout_spectrum: 0.92203
typography_spectrum: 0.5401355572976172
title: Sample
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.6700498952995986
  rhythmicContrast: 0.25
purpose: []
